version: '2.1'

services:

  importer:
    image: com.madewithtea/blockchainimporter:1.0.0
    restart: always
    environment:
      BLOCKCHAIN: "bitcoin"
      MODE: "lagging"
      LAG_BEHIND: "3"
      ENVIRONMENT: "production"
      POLL_TIME_MS: "1"
      BLOCKCHAIN_RPC_HOSTS: "176.9.61.19"
      BLOCKCHAIN_RPC_PORT: "8442"
      BLOCKCHAIN_RPC_USERNAME: "rpcuser"
      BLOCKCHAIN_RPC_PASSWORD: "5CcKHQMMIgVV56wSd5knN"
      SCHEMA_REGISTRY: "http://kafka-schema-registry:8081"
      BROKERS: "kafka1:19092"
      KAFKA_TRANSACTIONAL_ID: "importer"
      KAFKA_TOPIC_PREFIX: "bitcoin"
      DB_HOST: "db"
      DB_NAME: "importer"
      DB_USER: "importer"
      DB_PASS: "importer"
      DB_OFFSET_NAME: "bitcoin"

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: importer
      POSTGRES_USER: importer
      POSTGRES_PASSWORD: importer
    volumes:
    - ./minimal/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  kafka-schema-registry:
    image: confluentinc/cp-schema-registry:5.5.0
    hostname: kafka-schema-registry
    restart: always
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka1:19092
      SCHEMA_REGISTRY_HOST_NAME: kafka-schema-registry
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
    depends_on:
      - zoo1
      - kafka1

  zoo1:
    image: zookeeper:3.4.9
    hostname: zoo1
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=zoo1:2888:3888
    volumes:
      - ./minimal/zoo1/data:/data
      - ./minimal/zoo1/datalog:/datalog

  kafka1:
    image: confluentinc/cp-kafka:5.5.0
    hostname: kafka1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka1:19092,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

    volumes:
      - ./minimal/kafka1/data:/var/lib/kafka/data
    depends_on:
      - zoo1
